export default {
	ActionTypes: {
		/* GET FILTERS */
		GET_FILTERS: "GET_FILTERS",
		RECEIVE_FILTERS_SENDING:   "RECEIVE_FILTERS_SENDING",
		RECEIVE_FILTERS_SUCCEEDED: "RECEIVE_FILTERS_SUCCEEDED",
		RECEIVE_FILTERS_FAILED:    "RECEIVE_FILTERS_FAILED",

		/* GET EVENT BUCKETS METADATA */
		GET_EVENTBUCKETS_METADATA: "RECEIVE_EVENTBUCKETS_SENDING",
		RECEIVE_EVENTBUCKETS_SENDING:   "RECEIVE_EVENTBUCKETS_SENDING",
		RECEIVE_EVENTBUCKETS_SUCCEEDED: "RECEIVE_EVENTBUCKETS_SUCCEEDED",
		RECEIVE_EVENTBUCKETS_FAILED:    "RECEIVE_EVENTBUCKETS_FAILED",
	}
}