export default {
	ActionTypes: {
		/* GET FILTERS */
		GET_FILTERS: "GET_FILTERS",
		RECEIVE_FILTERS_SENDING:   "RECEIVE_FILTERS_SENDING",
		RECEIVE_FILTERS_SUCCEEDED: "RECEIVE_FILTERS_SUCCEEDED",
		RECEIVE_FILTERS_FAILED:    "RECEIVE_FILTERS_FAILED",

		/* GET EVENT BUCKETS METADATA */
		GET_EVENTBUCKETS_METADATA: "GET_EVENTBUCKETS_METADATA",
		RECEIVE_EVENTBUCKETS_SENDING:   "RECEIVE_EVENTBUCKETS_SENDING",
		RECEIVE_EVENTBUCKETS_SUCCEEDED: "RECEIVE_EVENTBUCKETS_SUCCEEDED",
		RECEIVE_EVENTBUCKETS_FAILED:    "RECEIVE_EVENTBUCKETS_FAILED",

		/* GET BUCKET DATA */
		GET_BUCKET_DATA: "GET_BUCKET_DATA",
		RECEIVE_BUCKET_SENDING:   "RECEIVE_BUCKET_SENDING",
		RECEIVE_BUCKET_SUCCEEDED: "RECEIVE_BUCKET_SUCCEEDED",
		RECEIVE_BUCKET_FAILED:    "RECEIVE_BUCKET_FAILED",

		/* SEND REPLY */
		SEND_REPLY: "SEND_REPLY",
		SEND_REPLY_SENDING:   "SEND_REPLY_SENDING",
		SEND_REPLY_SUCCEEDED: "SEND_REPLY_SUCCEEDED",
		SEND_REPLY_FAILED:    "SEND_REPLY_FAILED"
	}
}